Add test to check sources for specified repositories

diff --git a/jobs/miscellanea.txt.in b/jobs/miscellanea.txt.in
--- a/jobs/miscellanea.txt.in
+++ b/jobs/miscellanea.txt.in
@@ -64,3 +64,19 @@ requires: package.name == 'apport'
 command: if [ -d /var/crash ]; then if [ $(find /var/crash -type f | grep -v .lock | wc -l) -eq 0 ]; then echo "/var/crash is empty"; else echo `ls /var/crash`; false; fi; else echo "/var/crash does not exist"; fi
 _description: 
  Test that the /var/crash directory doesn't contain anything. Lists the files contained within if it does, or echoes the status of the directory (doesn't exist/is empty)
+
+plugin: shell
+name: miscellanea/sources-list
+command:
+ IFS=$','
+ result=0
+ for repository in $REPOSITORIES; do
+   if grep -q $repository $SOURCES_FILE
+   then
+     echo "$repository found in $SOURCES_FILE"
+   else
+     echo "$repository not found in $SOURCES_FILE"
+     result=1
+   fi
+ done
+ exit $result
