* jobs/info.txt.in: removed extraneous fwts_log job   jobs/miscellanea.txt.in: modified fwts_results.log job * scripts/disk_stats_test: some minor changes to output. Also, error output   now goes to stderr on test failure.

diff --git a/scripts/disk_stats_test b/scripts/disk_stats_test
--- a/scripts/disk_stats_test
+++ b/scripts/disk_stats_test
@@ -7,7 +7,7 @@ DISK="sda"
 
 check_return_code() {
     if [ "${1}" -ne "0" ]; then
-        echo "ERROR # ${1} : ${2}"
+        echo "ERROR: retval ${1} : ${2}" >/dev/stderr
         exit ${1}
     fi
 }
@@ -18,7 +18,7 @@ fi
 
 #Make sure we can run. This shouldn't run on removable drives (USB/Firewire)
 echo "Checking that we can run"
-[[ `cat /sys/block/$DISK/removable` == "1" ]] && echo "This should not be run on removable media" && exit 0
+[[ `cat /sys/block/$DISK/removable` == "1" ]] && echo "WARNING: This should not be run on removable media" && exit 0
 
 #Get some baseline stats for use later
 echo "Getting baseline stats"
@@ -62,10 +62,11 @@ SYS_STAT_END=`cat /sys/block/$DISK/stat`
 
 echo "Checking /proc/diskstats for changes"
 [[ "$PROC_STAT_BEGIN" != "$PROC_STAT_END" ]]
-check_return_code $? "Stats in Proc did not change"
+check_return_code $? "Stats in /proc/diskstats did not change"
 
 echo "Checking /sys/block/$DISK/stat for changes"
 [[ "$SYS_STAT_BEGIN" != "$SYS_STAT_END" ]]
-check_return_code $? "Stats in Sys did not change"
+check_return_code $? "Stats in /sys/block/$DISK/stat did not change"
 
+echo "PASS: Finished testing stats for $DISK"
 exit 0
