changed redirection to file descriptors

diff --git a/scripts/ipmi_test b/scripts/ipmi_test
--- a/scripts/ipmi_test
+++ b/scripts/ipmi_test
@@ -10,12 +10,12 @@ for module in ipmi_si ipmi_devintf ipmi_msghandler; do
         result=$?
         # if ipmi_si fails to load, it's safe to assume the system
         # has no BMC, so we'll just politely exit.
-        if [ $result -eq 1 ] && [ "$module" == "ipmi_si" ]; then
+        if [ $result -eq 1 ] && [ "$module" = "ipmi_si" ]; then
             echo "WARNING: No BMC found. Aborting."
             exit 0
         elif [ $result -eq 1 ]; then
-            echo "ERROR: Unable to load module $module" > dev/stderr
-            echo "Aborting IPMI test run." > /dev/stderr
+            echo "ERROR: Unable to load module $module" >&2
+            echo "Aborting IPMI test run." >&2
             exit 1
         else;
             echo "Successfully loaded module $module"
