scripts/optical_write_test: changed behaviour to timeout after 5 minutes rather than a few seconds to give testers a chance to complete the test without having to sit on top of the machine waiting. If tester doesn't hit the tray before timeout, the test makes a best efford to mount the disk itself and proceed. jobs/optical.txt.in: Cleared up text in the existing manual optical write tests and added two automated tests that can be used if desired (they still require the user to push the tray in after writing, but eliminate other steps)

diff --git a/scripts/optical_write_test b/scripts/optical_write_test
--- a/scripts/optical_write_test
+++ b/scripts/optical_write_test
@@ -60,19 +60,49 @@ burn_iso(){
 }
 
 check_disk(){
-    echo "Sleeping 15 seconds to allow drive to settle"
-    sleep 15
+    TIMEOUT=300
+    SLEEP_COUNT=0
+    INTERVAL=3
+
+    # Give the tester up to 5 minutes to reload the newly created CD/DVD
+    echo "Waiting up to 5 minutes for drive to be mounted ..."
+    while true; do
+        sleep $INTERVAL
+        SLEEP_COUNT=`expr $SLEEP_COUNT + $INTERVAL`
+        
+        mount $OPTICAL_DRIVE 2>&1 |egrep -q "already mounted"
+        rt=$?
+        if [ $rt -eq 0 ]; then
+            echo "Drive appears to be mounted now"
+            break
+        fi
+        
+        # If they exceed the timeout limit, make a best effort to load the tray
+        # in the next steps
+        if [ $SLEEP_COUNT -ge $TIMEOUT ]; then
+            echo "WARNING: TIMEOUT Exceeded and no mount detected!"
+            break
+        fi
+    done
+
+        
     echo "Deleting original data files ..."
     rm -rf $SAMPLE_FILE
     if [ ! -z "$(mount | grep $OPTICAL_DRIVE)" ]; then
         MOUNT_PT=$(mount | grep $OPTICAL_DRIVE | awk '{print $3}')
-        echo "Disk is already mounted to $MOUNT_PT"
+        echo "Disk is mounted to $MOUNT_PT"
     else
+        echo "Attempting best effort to mount $OPTICAL_DRIVE on my own"
         MOUNT_PT=$TEMP_DIR/mnt
         echo "Creating temp mount point: $MOUNT_PT ..."
         mkdir $MOUNT_PT
         echo "Mounting disk to mount point ..."
         mount $OPTICAL_DRIVE $MOUNT_PT
+        rt=$?
+        if [ $rt -ne 0 ]; then
+            echo "ERROR: Unable to re-mount $OPTICAL_DRIVE!" >&2
+            return 1
+        fi
     fi
     echo "Copying files from ISO ..."
     cp $MOUNT_PT/* $TEMP_DIR
@@ -103,6 +133,6 @@ get_sample_data || failed "Failed to copy sample data"
 generate_md5 || failed "Failed to generate initial md5"
 generate_iso || failed "Failed to create ISO image"
 burn_iso || failed "Failed to burn ISO image"
-check_disk || failed "Fiiles from Disk did not checksum"
+check_disk || failed "Failed to verify files on optical disk"
 cleanup || failed "Failed to clean up"
 exit 0
